SET TAB OFF
SET LINE 500
SELECT CS.CS_SEQNO, TM.DES, SP.SHDES, SN.SHDES,  CS.CS_DATE_BILLED, CS.CS_STAT_CHNG
FROM CONTRACT_ALL CO, CONTR_SERVICES CS, MPUTMTAB TM, MPUSPTAB SP, MPUSNTAB SN
WHERE CS.TMCODE = TM.TMCODE
AND TM.VSCODE = 1
AND CS.SPCODE = SP.SPCODE
AND CS.SNCODE = SN.SNCODE
AND CS.CO_ID = CO.CO_ID 
AND CO.CUSTOMER_ID = &1;

