UPDATE CUSTOMER_ALL SET LBC_DATE = NULL
WHERE CUSTOMER_ID = '&1';

UPDATE CONTR_SERVICES 
SET CS_DATE_BILLED = NULL
WHERE CO_ID IN (SELECT CO_ID 
                  FROM CONTRACT_ALL
                  WHERE CUSTOMER_ID = '&1');
